/**
 * Central mapping between CareFlow's healthcare domain model and the
 * underlying Zoho Projects custom modules / field API names.
 *
 * Zoho Projects is the ONLY system of record for CareFlow's business data.
 * Every module below is a Zoho Projects custom module; every field name is
 * the authoritative `field_name` returned by the Projects "Get Fields" API
 * (NOT the display name - Zoho auto-generates cf_XXXX names when a display
 * name collides with a reserved/default field name).
 *
 * IMPORTANT DEVIATION (documented in README "What Broke"):
 * Zoho Projects custom "picklist" fields return an unrecoverable 500 error
 * the moment a value is supplied on create/update, even for newly created
 * picklist fields. Every enum-like field below (status, priority, severity,
 * role, type, etc.) was therefore built as a `singleline` text field instead.
 * CareFlow enforces the valid enum values at the application layer (see the
 * ENUMS export) rather than relying on Zoho-side picklist validation.
 */

const PORTAL_ID = process.env.ZOHO_PORTAL_ID || "935571358";

const MODULES = {
  patient: "patient",
  carePlan: "care_plan",
  careTeam: "care_team_member",
  clinicalTask: "clinical_task",
  diagnostic: "diagnostic",
  treatment: "treatment_plan",
  appointment: "appointment",
  escalation: "escalation",
  progress: "care_progress_entry",
  auditLog: "audit_log_entry",
};

// field_name maps: healthcareConceptKey -> Zoho field_name
const FIELDS = {
  patient: {
    fullName: "name",
    patientCode: "patient_code",
    firstName: "patient_cf_0002",
    lastName: "patient_cf_0003",
    preferredName: "preferred_name",
    dateOfBirth: "date_of_birth",
    gender: "gender",
    phone: "phone_number",
    email: "patient_cf_0001",
    address: "address",
    emergencyContact: "emergency_contact",
    primaryPhysician: "primary_physician",
    primaryDiagnosis: "primary_diagnosis",
    secondaryConditions: "secondary_conditions",
    allergies: "allergies",
    riskLevel: "risk_level",
    insuranceProvider: "insurance_provider",
    insuranceId: "insurance_id",
    registrationDate: "registration_date",
    patientStatus: "patient_status",
    careCoordinator: "care_coordinator",
    preferredLanguage: "preferred_language",
    communicationPreference: "communication_preference",
  },
  carePlan: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    primaryCondition: "primary_condition",
    careType: "care_type",
    startDate: "care_plan_cf_0001",
    targetEndDate: "target_end_date",
    assignedCoordinator: "assigned_coordinator",
    priority: "care_plan_cf_0005",
    status: "plan_status",
    goal: "goal",
    notes: "care_plan_cf_0003",
    completionPct: "care_plan_cf_0004",
  },
  careTeam: {
    name: "name",
    teamMember: "team_member",
    role: "care_team_member_cf_0003",
    department: "care_team_member_cf_0002",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    assignmentDate: "assignment_date",
    responsibility: "responsibility",
    isPrimaryContact: "is_primary_contact",
    status: "member_status",
  },
  clinicalTask: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    assignedTo: "assigned_to",
    taskType: "task_type",
    priority: "clinical_task_cf_0004",
    dueDate: "clinical_task_cf_0001",
    status: "task_status",
    completedDate: "completed_date",
    notes: "clinical_task_cf_0003",
    escalationRequired: "escalation_required",
    dependency: "dependency",
  },
  diagnostic: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    testCategory: "test_category",
    orderedBy: "ordered_by",
    orderedDate: "ordered_date",
    scheduledDate: "scheduled_date",
    completedDate: "completed_date",
    status: "diagnostic_status",
    resultSummary: "result_summary",
    resultAvailability: "result_availability",
    priority: "diagnostic_cf_0003",
    notes: "diagnostic_cf_0002",
  },
  treatment: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    treatmentType: "treatment_type",
    prescribedBy: "prescribed_by",
    startDate: "treatment_plan_cf_0001",
    endDate: "treatment_plan_cf_0002",
    frequency: "frequency",
    status: "treatment_status",
    adherence: "adherence",
    notes: "treatment_plan_cf_0003",
  },
  appointment: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    provider: "provider",
    appointmentType: "appointment_type",
    date: "appointment_date",
    startTime: "appointment_cf_0001",
    endTime: "appointment_cf_0002",
    location: "location",
    mode: "mode",
    status: "appointment_status",
    reason: "reason",
    notes: "appointment_cf_0003",
  },
  escalation: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    source: "source",
    severity: "severity",
    description: "description",
    assignedTo: "assigned_to",
    dueDate: "escalation_cf_0001",
    status: "escalation_status",
    resolution: "resolution",
    resolvedBy: "resolved_by",
    resolvedDate: "resolved_date",
  },
  progress: {
    name: "name",
    patientId: "patient_id",
    patientName: "patient_name",
    carePlanId: "care_plan_id",
    metricDate: "metric_date",
    carePlanCompletionPct: "care_plan_completion_pct",
    taskCompletionPct: "task_completion_pct",
    treatmentAdherencePct: "treatment_adherence_pct",
    diagnosticCompletionPct: "diagnostic_completion_pct",
    appointmentAdherencePct: "appointment_adherence_pct",
    overdueTasksCount: "overdue_tasks_count",
    openEscalationsCount: "open_escalations_count",
    daysSinceLastActivity: "days_since_last_activity",
    nextMilestone: "next_milestone",
    goalProgressNotes: "goal_progress_notes",
  },
  auditLog: {
    name: "name",
    actionType: "action_type",
    entityType: "entity_type",
    entityId: "entity_id",
    entityName: "entity_name",
    actorUser: "actor_user",
    previousValue: "previous_value",
    newValue: "new_value",
  },
};

const ENUMS = {
  patientStatus: ["Active", "Inactive", "Discharged", "Transferred", "Archived"],
  riskLevel: ["Low", "Medium", "High", "Critical"],
  carePlanStatus: ["Draft", "Active", "On Hold", "Completed", "Cancelled"],
  careType: [
    "Chronic Care",
    "Post-Surgery",
    "Rehabilitation",
    "Preventive Care",
    "Oncology",
    "Cardiac Care",
    "Diabetes Management",
    "Elder Care",
    "Home Care",
    "General Care",
  ],
  priority: ["Low", "Medium", "High", "Urgent"],
  careTeamRole: [
    "Physician",
    "Nurse",
    "Care Coordinator",
    "Specialist",
    "Pharmacist",
    "Lab Technician",
    "Therapist",
    "Dietitian",
    "Administrator",
  ],
  careTeamStatus: ["Active", "On Leave", "Removed"],
  taskStatus: ["Not Started", "In Progress", "Blocked", "Completed", "Cancelled"],
  diagnosticStatus: [
    "Ordered",
    "Scheduled",
    "Sample Collected",
    "Processing",
    "Result Available",
    "Reviewed",
    "Cancelled",
  ],
  treatmentType: ["Medication", "Therapy", "Physiotherapy", "Lifestyle", "Diet", "Procedure", "Follow-up"],
  treatmentStatus: ["Planned", "Active", "Paused", "Completed", "Discontinued"],
  adherence: ["Good", "Needs Attention", "Poor", "Unknown"],
  appointmentType: ["Consultation", "Follow-up", "Diagnostic", "Therapy", "Procedure", "Care Review"],
  appointmentMode: ["In Person", "Video", "Phone"],
  appointmentStatus: [
    "Scheduled",
    "Confirmed",
    "Checked In",
    "Completed",
    "No Show",
    "Cancelled",
    "Rescheduled",
  ],
  escalationSeverity: ["Low", "Medium", "High", "Critical"],
  escalationStatus: ["Open", "Acknowledged", "In Progress", "Resolved", "Dismissed"],
  escalationSource: [
    "Critical Task Overdue",
    "Diagnostic Result Waiting for Review",
    "Patient Missed Appointment",
    "Treatment Adherence Issue",
    "High-Risk Patient Without Recent Activity",
    "Care Plan Approaching Target Date",
    "Unassigned Clinical Task",
    "Repeated Appointment Cancellation",
    "Required Follow-up Missed",
    "Critical Workflow Blocked",
  ],
};

module.exports = { PORTAL_ID, MODULES, FIELDS, ENUMS };
